// roles
export const ROLE_SUCCESS = 'ROLE_SUCCESS';
export const CREATE_ROLE = 'CREATE_ROLE';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const LOAD_ROLE_SUCCESS = 'LOAD_ROLE_SUCCESS';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';

// user
export const USER_SUCCESS = 'USER_SUCCESS';
export const CREATE_USER = 'CREATE_USER';
export const CURRENT_USER = 'CURRENT_USER';
export const EDIT_USER = 'EDIT_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FETCH_PROFILE = 'FETCH_PROFILE';


// DOCUMENT

export const DOCUMENT_SUCCESS = 'DOCUMENT_SUCCESS';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
export const LOAD_DOCUMENT_SUCCESS = 'LOAD_DOCUMENT_SUCCESS';
export const LOAD_OWN_DOCUMENT_SUCCESS = 'LOAD_OWN_DOCUMENT_SUCCESS';
export const UPDATE_OWN_DOCUMENT_SUCCESS = 'UPDATE_OWN_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
